### PR TITLE
bh - Make "New Image" form responsive (form inputs now stretch across…

### PR DESCRIPTION
**Pull request by blakeherrington**
I noticed that the new image form looked bad in mobile. I made this quick change so that the form inputs stretch all the way across the screen in mobile.

### CODE REVIEW

**Comment by bboe** [comment]
This is great. However, it's a little weird that the input fields gets smaller at one point when I resize the window. I don't know if it also did that before, but if it didn't then I would consider this a regression.

**Comment by blakeherrington** [comment]
@bboe Thanks for the note - I didn't realize that! I took a more thorough look and I think it's a bit more smooth now.

**Comment by bboe** [comment]
It appears to still go from:

screen shot 2016-04-21 at 15 07 07

to:

screen shot 2016-04-21 at 15 06 55

**Comment by blakeherrington** [comment]
Things should be correct now. Must've had a hiccup when amending... my bad :(

**Comment by bboe** [comment]
👍

**Pull request merged**
